name: 'Dastardly Scan Action'
description: 'Runs a Dastardly scan against a target site'
author: 'PortSwigger'
inputs:
  target-url:
    description: 'https://ginandjuice.shop'
    required: true
  output-filename:
    description: 'Dastardly testing'
    required: false
    default: dastardly-report.xml
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DASTARDLY_TARGET_URL: ${{ inputs.target-url }}
    DASTARDLY_OUTPUT_FILE: /github/workspace/${{ inputs.output-filename }}
branding:
  icon: 'activity'
  color: 'green'